INSERT INTO monitoring_class.class (class_code, class_name) VALUES ('IBDA1011', 'Pengantar Algoritma & Pemrograman');
INSERT INTO monitoring_class.class (class_code, class_name) VALUES ('IBDA1012', 'Struktur Data dan Algoritma');
INSERT INTO monitoring_class.class (class_code, class_name) VALUES ('IBDA1022', 'Organisasi dan Arsitektur Komputer');
INSERT INTO monitoring_class.class (class_code, class_name) VALUES ('IBDA2011', 'Analisis dan Perancangan Algoritma');
INSERT INTO monitoring_class.class (class_code, class_name) VALUES ('IBDA2012', 'Pemrograman Berbasis Web');
INSERT INTO monitoring_class.class (class_code, class_name) VALUES ('IBDA2021', 'Sistem Operasi');
INSERT INTO monitoring_class.class (class_code, class_name) VALUES ('IBDA2022', 'Jaringan Komputer');
INSERT INTO monitoring_class.class (class_code, class_name) VALUES ('IBDA2031', 'Pemrograman Berorientasi Objek');
INSERT INTO monitoring_class.class (class_code, class_name) VALUES ('IBDA2041', 'Sistem Basis Data');
INSERT INTO monitoring_class.class (class_code, class_name) VALUES ('IBDA3011', 'Rekayasa Perangkat Lunak');
INSERT INTO monitoring_class.class (class_code, class_name) VALUES ('IBDA3021', 'Interaksi Manusia dan Komputer');
INSERT INTO monitoring_class.class (class_code, class_name) VALUES ('IBDA3031', 'Pengembangan Web Modern');
INSERT INTO monitoring_class.class (class_code, class_name) VALUES ('IBDA3041', 'Teori Automata');
INSERT INTO monitoring_class.class (class_code, class_name) VALUES ('IBDA3212', 'Virtualisasi');
INSERT INTO monitoring_class.class (class_code, class_name) VALUES ('IDIS1011', 'Pemikiran & Pembelajaran Kristen');
INSERT INTO monitoring_class.class (class_code, class_name) VALUES ('IDIS1031', 'Penatalayanan I (Kewirausahaan)');
INSERT INTO monitoring_class.class (class_code, class_name) VALUES ('IDIS2031', 'Tuhan, Penciptaan, dan Kemanusiaan');
INSERT INTO monitoring_class.class (class_code, class_name) VALUES ('IEE2022', 'Mikrokontroler dan Sensor I');
INSERT INTO monitoring_class.class (class_code, class_name) VALUES ('MATH1022', 'Matematika Diskrit');
INSERT INTO monitoring_class.class (class_code, class_name) VALUES ('MATH1042', 'Peluang dan Statistika');
INSERT INTO monitoring_class.class (class_code, class_name) VALUES ('MATH1061', 'Kalkulus I');
INSERT INTO monitoring_class.class (class_code, class_name) VALUES ('MATH1062', 'Kalkulus II');
INSERT INTO monitoring_class.class (class_code, class_name) VALUES ('MATH2031', 'Aljabar Linear');
INSERT INTO monitoring_class.class (class_code, class_name) VALUES ('PHED1014', 'Pendidikan Jasmani I');
INSERT INTO monitoring_class.class (class_code, class_name) VALUES ('PHED2014', 'Pendidikan Jasmani II');
INSERT INTO monitoring_class.class (class_code, class_name) VALUES ('PHIL1031', 'Iman Kristen dan Filsafat Barat I');
INSERT INTO monitoring_class.class (class_code, class_name) VALUES ('PHIL1062', 'Pengantar Logika');
INSERT INTO monitoring_class.class (class_code, class_name) VALUES ('PHYS1011', 'Fisika I');
INSERT INTO monitoring_class.class (class_code, class_name) VALUES ('RHET1011', 'Bahasa Indonesia');
INSERT INTO monitoring_class.class (class_code, class_name) VALUES ('RHET1021', 'Membaca dan Menulis Kritis/Bahasa Inggris I');
INSERT INTO monitoring_class.class (class_code, class_name) VALUES ('SOC1011', 'Kewarganegaraan');
INSERT INTO monitoring_class.class (class_code, class_name) VALUES ('THEO1011', 'Survei Teologi Reformed');
INSERT INTO monitoring_class.class (class_code, class_name) VALUES ('THEO2011', 'Doktrin Kristus dan Keselamatan');
INSERT INTO monitoring_class.class (class_code, class_name) VALUES ('THEO2021', 'Doktrin Roh Kudus Gereja');
INSERT INTO monitoring_class.class (class_code, class_name) VALUES ('THEO2031', 'Etika Reformed');
